apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: security-lab
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-token
  namespace: security-lab
  annotations:
    kubernetes.io/service-account.name: developer
type: kubernetes.io/service-account-token