apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
  namespace: security-lab
  labels:
    app: insecure-demo
spec:
  containers:
  - name: insecure-container
    image: nginx:latest
    ports:
    - containerPort: 80
    securityContext:
      # INSECURE: Running as root
      runAsUser: 0
      # INSECURE: Allowing privilege escalation
      allowPrivilegeEscalation: true
      # INSECURE: Running in privileged mode
      privileged: true
      # INSECURE: Adding dangerous capabilities
      capabilities:
        add:
        - SYS_ADMIN
        - NET_ADMIN
    # INSECURE: No resource limits
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  # INSECURE: Mounting host filesystem
  - name: host-root
    hostPath:
      path: /
      type: Directory