apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-lab-quota
  namespace: security-lab
spec:
  hard:
    # Compute resources
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    
    # Storage resources
    requests.storage: 10Gi
    persistentvolumeclaims: "4"
    
    # Object counts
    pods: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"
    
    # Security-related limits
    count/pods: "10"
    count/services.nodeports: "0"  # Không cho phép NodePort
    count/services.loadbalancers: "1"  # Giới hạn LoadBalancer
---
apiVersion: v1
kind: LimitRange
metadata:
  name: security-lab-limits
  namespace: security-lab
spec:
  limits:
  - default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "1"
      memory: "1Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "2Gi"
    type: Pod