apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: web-app
    pattern: sidecar
spec:
  containers:
  # Main application container
  - name: web-server
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    - name: shared-data
      mountPath: /usr/share/nginx/html
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5

  # Sidecar: Log processing
  - name: log-processor
    image: fluent/fluent-bit:1.9
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
      readOnly: true
    - name: fluent-bit-config
      mountPath: /fluent-bit/etc
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "200m"

  # Sidecar: Metrics exporter
  - name: metrics-exporter
    image: nginx/nginx-prometheus-exporter:0.10.0
    args:
      - -nginx.scrape-uri=http://localhost/nginx_status
    ports:
    - containerPort: 9113
      name: metrics
    resources:
      requests:
        memory: "16Mi"
        cpu: "50m"
      limits:
        memory: "32Mi"
        cpu: "100m"

  # Init container: Setup
  initContainers:
  - name: setup
    image: busybox:1.35
    command:
    - sh
    - -c
    - |
      echo "Setting up application..."
      echo "<h1>Hello from Multi-Container Pod!</h1>" > /shared/index.html
      echo "Setup completed at $(date)" >> /shared/index.html
    volumeMounts:
    - name: shared-data
      mountPath: /shared

  volumes:
  - name: shared-logs
    emptyDir: {}
  - name: shared-data
    emptyDir: {}
  - name: fluent-bit-config
    configMap:
      name: fluent-bit-config

  restartPolicy: Always
  dnsPolicy: ClusterFirst

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off

    [INPUT]
        Name              tail
        Path              /var/log/nginx/*.log
        Parser            nginx
        Tag               nginx.*
        Refresh_Interval  5

    [OUTPUT]
        Name  stdout
        Match *

  parsers.conf: |
    [PARSER]
        Name        nginx
        Format      regex
        Regex       ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z