apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-production-backup
  namespace: velero
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  template:
    includedNamespaces:
    - production
    - monitoring
    excludedResources:
    - events
    - events.events.k8s.io
    - nodes
    - clusterroles
    - clusterrolebindings
    storageLocation: default
    ttl: 720h0m0s  # 30 days retention
    snapshotVolumes: true
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: weekly-full-backup
  namespace: velero
spec:
  schedule: "0 1 * * 0"  # Weekly on Sunday at 1 AM
  template:
    includedNamespaces:
    - production
    - staging
    - monitoring
    - kube-system
    excludedResources:
    - events
    - events.events.k8s.io
    storageLocation: default
    ttl: 2160h0m0s  # 90 days retention
    snapshotVolumes: true
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-critical-backup
  namespace: velero
spec:
  schedule: "0 * * * *"  # Every hour
  template:
    includedNamespaces:
    - production
    labelSelector:
      matchLabels:
        backup: critical
    excludedResources:
    - events
    - events.events.k8s.io
    storageLocation: default
    ttl: 168h0m0s  # 7 days retention
    snapshotVolumes: false  # Faster backup without volumes