apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: production
spec:
  hard:
    # Compute resources
    requests.cpu: "50"
    requests.memory: 100Gi
    limits.cpu: "100"
    limits.memory: 200Gi
    
    # Storage resources
    requests.storage: 500Gi
    persistentvolumeclaims: "20"
    
    # Object counts
    pods: "50"
    services: "20"
    secrets: "50"
    configmaps: "50"
    
    # Load balancers (expensive)
    services.loadbalancers: "3"
    
    # Node ports (security risk)
    services.nodeports: "0"
    
    # Ingress controllers
    count/ingresses.extensions: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    # Reduced resources for staging
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    
    requests.storage: 200Gi
    persistentvolumeclaims: "10"
    
    pods: "30"
    services: "15"
    secrets: "30"
    configmaps: "30"
    
    services.loadbalancers: "1"
    services.nodeports: "0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    # Generous resources for monitoring
    requests.cpu: "30"
    requests.memory: 60Gi
    limits.cpu: "60"
    limits.memory: 120Gi
    
    requests.storage: 1Ti
    persistentvolumeclaims: "15"
    
    pods: "40"
    services: "25"
    secrets: "40"
    configmaps: "40"