apiVersion: v1
kind: ConfigMap
metadata:
  name: production-alerts
  namespace: monitoring
data:
  production.rules: |
    groups:
    - name: production.critical
      rules:
      # High error rate
      - alert: HighErrorRate
        expr: |
          (
            rate(http_requests_total{status=~"5.."}[5m]) /
            rate(http_requests_total[5m])
          ) > 0.01
        for: 5m
        labels:
          severity: critical
          team: sre
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.service }}"
          runbook_url: "https://runbooks.company.com/high-error-rate"
      
      # High latency
      - alert: HighLatency
        expr: |
          histogram_quantile(0.95,
            rate(http_request_duration_seconds_bucket[5m])
          ) > 0.5
        for: 10m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "High latency detected"
          description: "95th percentile latency is {{ $value }}s for {{ $labels.service }}"
      
      # Pod crash looping
      - alert: PodCrashLooping
        expr: |
          rate(kube_pod_container_status_restarts_total[15m]) * 60 * 15 > 0
        for: 5m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "Pod is crash looping"
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"
      
      # Node not ready
      - alert: NodeNotReady
        expr: kube_node_status_condition{condition="Ready",status="true"} == 0
        for: 5m
        labels:
          severity: critical
          team: infrastructure
        annotations:
          summary: "Node is not ready"
          description: "Node {{ $labels.node }} has been not ready for more than 5 minutes"
      
      # High memory usage
      - alert: HighMemoryUsage
        expr: |
          (
            container_memory_usage_bytes{container!=""} /
            container_spec_memory_limit_bytes{container!=""} * 100
          ) > 90
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High memory usage"
          description: "Container {{ $labels.container }} in {{ $labels.namespace }}/{{ $labels.pod }} is using {{ $value }}% of memory"
      
      # High CPU usage
      - alert: HighCPUUsage
        expr: |
          (
            rate(container_cpu_usage_seconds_total{container!=""}[5m]) /
            container_spec_cpu_quota{container!=""} * container_spec_cpu_period{container!=""} * 100
          ) > 90
        for: 15m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High CPU usage"
          description: "Container {{ $labels.container }} in {{ $labels.namespace }}/{{ $labels.pod }} is using {{ $value }}% of CPU"
      
      # Disk space low
      - alert: DiskSpaceLow
        expr: |
          (
            node_filesystem_avail_bytes{mountpoint="/"} /
            node_filesystem_size_bytes{mountpoint="/"} * 100
          ) < 10
        for: 5m
        labels:
          severity: critical
          team: infrastructure
        annotations:
          summary: "Disk space low"
          description: "Node {{ $labels.instance }} has less than 10% disk space remaining"
      
      # PVC usage high
      - alert: PVCUsageHigh
        expr: |
          (
            kubelet_volume_stats_used_bytes /
            kubelet_volume_stats_capacity_bytes * 100
          ) > 85
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "PVC usage high"
          description: "PVC {{ $labels.persistentvolumeclaim }} in {{ $labels.namespace }} is {{ $value }}% full"
      
      # Deployment replica mismatch
      - alert: DeploymentReplicaMismatch
        expr: |
          kube_deployment_spec_replicas !=
          kube_deployment_status_replicas_available
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Deployment replica mismatch"
          description: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has {{ $value }} replicas available, expected {{ $labels.spec_replicas }}"
      
      # Certificate expiring soon
      - alert: CertificateExpiringSoon
        expr: |
          (cert_exporter_not_after - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
          team: security
        annotations:
          summary: "Certificate expiring soon"
          description: "Certificate {{ $labels.name }} will expire in {{ $value }} days"
    
    - name: production.slo
      rules:
      # SLO burn rate alerts
      - alert: SLOBurnRateHigh
        expr: |
          (
            1 - (
              rate(http_requests_total{status!~"5.."}[1h]) /
              rate(http_requests_total[1h])
            )
          ) > 0.001
        for: 5m
        labels:
          severity: critical
          team: sre
        annotations:
          summary: "SLO burn rate is high"
          description: "Error budget is being consumed rapidly for {{ $labels.service }}"