apiVersion: v1
kind: Pod
metadata:
  name: fixed-crashloop-pod
  labels:
    app: crashloop-demo
spec:
  containers:
  - name: app
    image: nginx:alpine
    # Fixed command that will run successfully
    command: ["nginx", "-g", "daemon off;"]
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    # Fixed liveness probe
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    # Added readiness probe
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
  restartPolicy: Always