apiVersion: v1
kind: Pod
metadata:
  name: crashloop-pod
  labels:
    app: crashloop-demo
spec:
  containers:
  - name: app
    image: busybox:latest
    # Command that will fail immediately
    command: ["sh", "-c", "echo 'Starting...' && exit 1"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    # Liveness probe that will fail
    livenessProbe:
      exec:
        command:
        - cat
        - /nonexistent/file
      initialDelaySeconds: 5
      periodSeconds: 5
  restartPolicy: Always