apiVersion: v1
kind: Pod
metadata:
  name: imagepull-pod
  labels:
    app: imagepull-demo
spec:
  containers:
  - name: app
    # Non-existent image
    image: nonexistent-registry.com/nonexistent-image:latest
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
  # Non-existent image pull secret
  imagePullSecrets:
  - name: nonexistent-secret