apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-app
  labels:
    app: network-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: network-demo
  template:
    metadata:
      labels:
        app: network-demo
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: network-service
  labels:
    app: network-demo
spec:
  selector:
    # Wrong selector - doesn't match pod labels
    app: wrong-label
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP