apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    # Pod Security Standards
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/enforce-version: latest
    
    # Environment labels
    environment: production
    tier: critical
    
    # Cost allocation
    cost-center: engineering
    team: platform
    
    # Compliance
    compliance: required
    data-classification: confidential
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    # Pod Security Standards - less restrictive for staging
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/enforce-version: latest
    
    environment: staging
    tier: non-critical
    cost-center: engineering
    team: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    # System namespace - privileged for monitoring tools
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    
    environment: system
    tier: critical
    cost-center: infrastructure
    team: sre