apiVersion: v1
kind: ServiceAccount
metadata:
  name: production-developer
  namespace: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: production-sre
  namespace: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: production-developer-role
rules:
# Read access to most resources
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
# Limited write access
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "update", "patch"]
# No delete permissions for safety
# Logs access for debugging
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
# Exec access for debugging (restricted)
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: production-sre-role
rules:
# Full access to production namespace
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: production-sre-cluster-role
rules:
# Read access to cluster resources
- apiGroups: [""]
  resources: ["nodes", "namespaces", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
# Metrics access
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]
# Custom metrics access
- apiGroups: ["custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: production-developer-binding
  namespace: production
subjects:
- kind: ServiceAccount
  name: production-developer
  namespace: production
roleRef:
  kind: Role
  name: production-developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: production-sre-binding
  namespace: production
subjects:
- kind: ServiceAccount
  name: production-sre
  namespace: production
roleRef:
  kind: Role
  name: production-sre-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: production-sre-cluster-binding
subjects:
- kind: ServiceAccount
  name: production-sre
  namespace: production
roleRef:
  kind: ClusterRole
  name: production-sre-cluster-role
  apiGroup: rbac.authorization.k8s.io