apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.example.com
spec:
  group: example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: string
                enum: ["small", "medium", "large"]
                description: "Database size"
              version:
                type: string
                pattern: '^[0-9]+\.[0-9]+$'
                description: "Database version"
              replicas:
                type: integer
                minimum: 1
                maximum: 10
                description: "Number of replicas"
              storage:
                type: string
                pattern: '^[0-9]+Gi$'
                description: "Storage size"
            required:
            - size
            - version
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Failed"]
              message:
                type: string
              replicas:
                type: integer
              readyReplicas:
                type: integer
    additionalPrinterColumns:
    - name: Size
      type: string
      jsonPath: .spec.size
    - name: Version
      type: string
      jsonPath: .spec.version
    - name: Replicas
      type: integer
      jsonPath: .spec.replicas
    - name: Ready
      type: integer
      jsonPath: .status.readyReplicas
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
    - db